import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import {
  LARKINS_SYSTEM,
  scriptedReply,
  briefComplete,
  type ChatMessage,
} from "@/lib/claude";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface RequestBody {
  messages: ChatMessage[];
}

/**
 * Larkins conversation endpoint.
 *
 * With ANTHROPIC_API_KEY set, replies are generated by Claude using the
 * Larkins system prompt. Without a key, a deterministic scripted flow
 * collects the same five-question brief — the console always works.
 */
export async function POST(req: Request) {
  let body: RequestBody;
  try {
    body = (await req.json()) as RequestBody;
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const messages = Array.isArray(body.messages) ? body.messages : [];
  if (messages.length === 0) {
    return NextResponse.json({ error: "No messages provided" }, { status: 400 });
  }

  const done = briefComplete(messages);
  const apiKey = process.env.ANTHROPIC_API_KEY;

  // No key — deterministic scripted brief.
  if (!apiKey) {
    return NextResponse.json({ reply: scriptedReply(messages), done });
  }

  // Live Claude generation.
  try {
    const client = new Anthropic({ apiKey });

    // The Messages API must start with a user turn — drop the leading
    // assistant greeting that the client renders locally.
    const firstUser = messages.findIndex((m) => m.role === "user");
    const conversation =
      firstUser === -1 ? messages : messages.slice(firstUser);

    const response = await client.messages.create({
      model: process.env.ANTHROPIC_MODEL ?? "claude-opus-4-7",
      max_tokens: 700,
      system: LARKINS_SYSTEM,
      messages: conversation.map((m) => ({
        role: m.role,
        content: m.content,
      })),
    });

    const reply = response.content
      .filter((block): block is Anthropic.TextBlock => block.type === "text")
      .map((block) => block.text)
      .join("\n")
      .trim();

    return NextResponse.json({
      reply: reply || scriptedReply(messages),
      done,
    });
  } catch (error) {
    // Any API failure degrades gracefully to the scripted flow.
    console.error("Larkins API error:", error);
    return NextResponse.json({ reply: scriptedReply(messages), done });
  }
}
